### ISSUE TITLE
Build Commands are ignored

### ISSUE THREAD

**Issue by joerghall** [rcook/ibt#16]
I tried to execute the following sample to check if docker commands work. I don't see the commands being executed.

```
docker:
  image: kubeworld-build-container:1.2.0
  build:
   -  groupadd -g 981 docker_group_host
    - usermod -a -G docker_group_host joerghall
```
